### ISSUE TITLE
train_dataset, eval_dataset, test_dataset的疑问

### ISSUE THREAD

**Issue by PunkMale** [JackYFL/DISC#10]
请问作者：
clothing1m和webvision数据集的dataloader中包含`train_dataset, eval_dataset, test_dataset`，而其他数据集只有`train_dataset, test_dataset`，请问`eval_dataset`的引入有什么特殊作用吗？帮助选择最佳超参数？
期待解答🌹

**Comment by JackYFL** [comment]
你好，对于clothing1M数据集来说，一般使用验证集来选择超参数；对于webvision数据集来说，它自带的验证集也属于要评测的数据集。祝好~

**Comment by PunkMale** [comment]
感谢指导！那么对于clothing1M数据集是选择验证集最好的结果对应epoch的测试集的结果进行报道吗？

**Comment by JackYFL** [comment]
是的。

**Comment by PunkMale** [comment]
好的，非常感谢🙏🙏🙏
