### ISSUE TITLE
关于如何选择报道的结果

### ISSUE THREAD

**Issue by PunkMale** [JackYFL/DISC#11]
作者您好！
我看您的结果中，有的结果是`mean±std`格式，而有的数据集只有一个结果。
请问：
1. 在一次实验中，有效结果是最后一个吗（没有验证集的话）？
2. 对于有验证集的数据集（如clothing1M），在一次实验中，是不是取验证集最好的epoch的测试集结果？
3. 在您报道的实验结果中，`mean±std`是如何计算的？
4. 对于您报道的没有std的结果，只训一次得结果就行了吗？

感谢您的解答！🌹🌹🌹

**Comment by JackYFL** [comment]
你好，
1. 在没有验证集的情况下，比如CIFAR数据集，我们取后10个epoch的均值和方差来作为最后的结果；
2. 在有验证集的情况下取验证集最好的epoch的测试集结果；
3. mean，std是最后10个epoch acc的mean和std；
4. 是的，不过要控制seed不变。
祝好~

**Comment by PunkMale** [comment]
非常感谢您细心的解答！
我漏了一个问题，就是对于没有方差的结果，且该数据集没有验证集，是直接报道最后10个epoch的均值就行了吗？

**Comment by JackYFL** [comment]
是的，这样是为了保证实验的可复现性。

**Comment by PunkMale** [comment]
好的，非常感谢您的耐心！🙏🙏🙏
祝您科研一切顺利！

**Comment by JackYFL** [comment]
谢谢，也祝您科研顺利~
