### ISSUE TITLE
Problems replicating cifar-100 sym 80% noise

### ISSUE THREAD

**Issue by oscaroca** [JackYFL/DISC#14]
Hi,

We have tried to replicate the results of the supplementary paper for cifar-100 with 80% symmetrical noise using the parameters provided in the paper and those already in the code, but we have not been able to obtain similar to those reported consistently In neither of the two types of symmetrical noise (with and without clean samples in the noise).

Results obtained in 4 runs with DISC and the config in supplementary:
Average last 10 epoch:
Mean accuracy: 54.4905
Standard deviation of accuracy: ±1.938808
Best epoch:
Accuracy: 55.0585
Standard deviation of accuracy: ±2.029241

Despite following the parameters mentioned both in the document and as modified by the code provided, we have not been able to replicate the expected results. We would like to ask you if you can provide us with the execution parameters and the config file to be able to replicate the results for a specific cifar-100 sym 80% noise.

Thanks in advance.

**Comment by JackYFL** [comment]
Hi, sorry for the late response. The difference in the results may also be related to the GPUs. Moreover, I also found that the results under large noise settings change significantly. So I think you can report the results of your reproduction.
