### ISSUE TITLE
Question about Dynamic Instance-Specific Threshold

### ISSUE THREAD

**Issue by oscaroca** [JackYFL/DISC#4]
Hi, I have a question about the final calculation of the Threshold equation 4 in the paper and line 17 in the algorithm found in supplemental. In this step you call the max function for two positives values, however in the code you use the min. Might this be an error?
I also wanted to ask for the 0.99 / 0.90 difference, but you just corrected it.
Thank you, and congratulations on your awesome work.

**Comment by JackYFL** [comment]
We appreciate for pointing out this error in the paper. Yes, the function in equation 4 should be 'min' rather than 'max' since we want 0.99 to be the upper bound.

**Comment by oscaroca** [comment]
Thanks for the answer ^^
