### ISSUE TITLE
Inconsistent Calculation of ws_threshold

### ISSUE THREAD

**Issue by Externalhappy** [JackYFL/DISC#8]
In your paper, you compute `ws_threshold` using the `max` function. However, in your code on line 347 in DiCS.py, you use the min function instead:
`ws_threshold = torch.min(ws_threshold, torch.tensor(0.99).to(self.device))`. 
Which one is the correct one?

**Comment by JackYFL** [comment]
Thank you for your interest in our research. It has come to our attention that there is a typographical error in our paper. The term 'max' was inadvertently used and should be corrected to 'min'. We appreciate your understanding and apologize for any confusion this may have caused.
